INSERT INTO CountryInTheWorlds(Country,IsEnable) VALUES('Afghanistan',1)
INSERT INTO CountryInTheWorlds(Country,IsEnable) VALUES('Aland Islands',1)
INSERT INTO CountryInTheWorlds(Country,IsEnable) VALUES('Albania',1)
INSERT INTO CountryInTheWorlds(Country,IsEnable) VALUES('Algeria',1)
INSERT INTO CountryInTheWorlds(Country,IsEnable) VALUES('American Samoa',1)
INSERT INTO CountryInTheWorlds(Country,IsEnable) VALUES('Andorra',1)
INSERT INTO CountryInTheWorlds(Country,IsEnable) VALUES('Angola',1)
INSERT INTO CountryInTheWorlds(Country,IsEnable) VALUES('Anguilla',1)
INSERT INTO CountryInTheWorlds(Country,IsEnable) VALUES('Antarctica',1)
INSERT INTO CountryInTheWorlds(Country,IsEnable) VALUES('Antigua and Barbuda',1)
INSERT INTO CountryInTheWorlds(Country,IsEnable) VALUES('Argentina',1)
INSERT INTO CountryInTheWorlds(Country,IsEnable) VALUES('Armenia',1)
INSERT INTO CountryInTheWorlds(Country,IsEnable) VALUES('Aruba',1)
INSERT INTO CountryInTheWorlds(Country,IsEnable) VALUES('Australia',1)
INSERT INTO CountryInTheWorlds(Country,IsEnable) VALUES('Austria',1)
INSERT INTO CountryInTheWorlds(Country,IsEnable) VALUES('Azerbaijan',1)
INSERT INTO CountryInTheWorlds(Country,IsEnable) VALUES('Bahamas',1)
INSERT INTO CountryInTheWorlds(Country,IsEnable) VALUES('Bahrain',1)
INSERT INTO CountryInTheWorlds(Country,IsEnable) VALUES('Bangladesh',1)
INSERT INTO CountryInTheWorlds(Country,IsEnable) VALUES('Barbados',1)
INSERT INTO CountryInTheWorlds(Country,IsEnable) VALUES('Belarus',1)
INSERT INTO CountryInTheWorlds(Country,IsEnable) VALUES('Belgium',1)
INSERT INTO CountryInTheWorlds(Country,IsEnable) VALUES('Belize',1)
INSERT INTO CountryInTheWorlds(Country,IsEnable) VALUES('Benin',1)
INSERT INTO CountryInTheWorlds(Country,IsEnable) VALUES('Bermuda',1)
INSERT INTO CountryInTheWorlds(Country,IsEnable) VALUES('Bhutan',1)
INSERT INTO CountryInTheWorlds(Country,IsEnable) VALUES('Bolivia',1)
INSERT INTO CountryInTheWorlds(Country,IsEnable) VALUES('Bonaire, Sint Eustatius and Saba',1)
INSERT INTO CountryInTheWorlds(Country,IsEnable) VALUES('Bosnia and Herzegovina',1)
INSERT INTO CountryInTheWorlds(Country,IsEnable) VALUES('Botswana',1)
INSERT INTO CountryInTheWorlds(Country,IsEnable) VALUES('Bouvet Island',1)
INSERT INTO CountryInTheWorlds(Country,IsEnable) VALUES('Brazil',1)
INSERT INTO CountryInTheWorlds(Country,IsEnable) VALUES('British Indian Ocean Territory',1)
INSERT INTO CountryInTheWorlds(Country,IsEnable) VALUES('Brunei',1)
INSERT INTO CountryInTheWorlds(Country,IsEnable) VALUES('Bulgaria',1)
INSERT INTO CountryInTheWorlds(Country,IsEnable) VALUES('Burkina Faso',1)
INSERT INTO CountryInTheWorlds(Country,IsEnable) VALUES('Burundi',1)
INSERT INTO CountryInTheWorlds(Country,IsEnable) VALUES('Cambodia',0)
INSERT INTO CountryInTheWorlds(Country,IsEnable) VALUES('Cameroon',1)
INSERT INTO CountryInTheWorlds(Country,IsEnable) VALUES('Canada',1)
INSERT INTO CountryInTheWorlds(Country,IsEnable) VALUES('Cape Verde',1)
INSERT INTO CountryInTheWorlds(Country,IsEnable) VALUES('Cayman Islands',1)
INSERT INTO CountryInTheWorlds(Country,IsEnable) VALUES('Central African Republic',1)
INSERT INTO CountryInTheWorlds(Country,IsEnable) VALUES('Chad',1)
INSERT INTO CountryInTheWorlds(Country,IsEnable) VALUES('Chile',1)
INSERT INTO CountryInTheWorlds(Country,IsEnable) VALUES('China',1)
INSERT INTO CountryInTheWorlds(Country,IsEnable) VALUES('Christmas Island',1)
INSERT INTO CountryInTheWorlds(Country,IsEnable) VALUES('Cocos (Keeling) Islands',1)
INSERT INTO CountryInTheWorlds(Country,IsEnable) VALUES('Colombia',1)
INSERT INTO CountryInTheWorlds(Country,IsEnable) VALUES('Comoros',1)
INSERT INTO CountryInTheWorlds(Country,IsEnable) VALUES('Congo',1)
INSERT INTO CountryInTheWorlds(Country,IsEnable) VALUES('Cook Islands',1)
INSERT INTO CountryInTheWorlds(Country,IsEnable) VALUES('Costa Rica',1)
INSERT INTO CountryInTheWorlds(Country,IsEnable) VALUES('Ivory Coast',1)
INSERT INTO CountryInTheWorlds(Country,IsEnable) VALUES('Croatia',1)
INSERT INTO CountryInTheWorlds(Country,IsEnable) VALUES('Cuba',1)
INSERT INTO CountryInTheWorlds(Country,IsEnable) VALUES('Curacao',1)
INSERT INTO CountryInTheWorlds(Country,IsEnable) VALUES('Cyprus',1)
INSERT INTO CountryInTheWorlds(Country,IsEnable) VALUES('Czech Republic',1)
INSERT INTO CountryInTheWorlds(Country,IsEnable) VALUES('Democratic Republic of the Congo',1)
INSERT INTO CountryInTheWorlds(Country,IsEnable) VALUES('Denmark',1)
INSERT INTO CountryInTheWorlds(Country,IsEnable) VALUES('Djibouti',1)
INSERT INTO CountryInTheWorlds(Country,IsEnable) VALUES('Dominica',1)
INSERT INTO CountryInTheWorlds(Country,IsEnable) VALUES('Dominican Republic',1)
INSERT INTO CountryInTheWorlds(Country,IsEnable) VALUES('Ecuador',1)
INSERT INTO CountryInTheWorlds(Country,IsEnable) VALUES('Egypt',1)
INSERT INTO CountryInTheWorlds(Country,IsEnable) VALUES('El Salvador',1)
INSERT INTO CountryInTheWorlds(Country,IsEnable) VALUES('Equatorial Guinea',1)
INSERT INTO CountryInTheWorlds(Country,IsEnable) VALUES('Eritrea',1)
INSERT INTO CountryInTheWorlds(Country,IsEnable) VALUES('Estonia',1)
INSERT INTO CountryInTheWorlds(Country,IsEnable) VALUES('Ethiopia',1)
INSERT INTO CountryInTheWorlds(Country,IsEnable) VALUES('Falkland Islands (Malvinas)',1)
INSERT INTO CountryInTheWorlds(Country,IsEnable) VALUES('Faroe Islands',1)
INSERT INTO CountryInTheWorlds(Country,IsEnable) VALUES('Fiji',1)
INSERT INTO CountryInTheWorlds(Country,IsEnable) VALUES('Finland',1)
INSERT INTO CountryInTheWorlds(Country,IsEnable) VALUES('France',1)
INSERT INTO CountryInTheWorlds(Country,IsEnable) VALUES('French Guiana',1)
INSERT INTO CountryInTheWorlds(Country,IsEnable) VALUES('French Polynesia',1)
INSERT INTO CountryInTheWorlds(Country,IsEnable) VALUES('French Southern Territories',1)
INSERT INTO CountryInTheWorlds(Country,IsEnable) VALUES('Gabon',1)
INSERT INTO CountryInTheWorlds(Country,IsEnable) VALUES('Gambia',1)
INSERT INTO CountryInTheWorlds(Country,IsEnable) VALUES('Georgia',1)
INSERT INTO CountryInTheWorlds(Country,IsEnable) VALUES('Germany',1)
INSERT INTO CountryInTheWorlds(Country,IsEnable) VALUES('Ghana',1)
INSERT INTO CountryInTheWorlds(Country,IsEnable) VALUES('Gibraltar',1)
INSERT INTO CountryInTheWorlds(Country,IsEnable) VALUES('Greece',1)
INSERT INTO CountryInTheWorlds(Country,IsEnable) VALUES('Greenland',1)
INSERT INTO CountryInTheWorlds(Country,IsEnable) VALUES('Grenada',1)
INSERT INTO CountryInTheWorlds(Country,IsEnable) VALUES('Guadaloupe',1)
INSERT INTO CountryInTheWorlds(Country,IsEnable) VALUES('Guam',1)
INSERT INTO CountryInTheWorlds(Country,IsEnable) VALUES('Guatemala',1)
INSERT INTO CountryInTheWorlds(Country,IsEnable) VALUES('Guernsey',1)
INSERT INTO CountryInTheWorlds(Country,IsEnable) VALUES('Guinea',1)
INSERT INTO CountryInTheWorlds(Country,IsEnable) VALUES('Guinea-Bissau',1)
INSERT INTO CountryInTheWorlds(Country,IsEnable) VALUES('Guyana',1)
INSERT INTO CountryInTheWorlds(Country,IsEnable) VALUES('Haiti',1)
INSERT INTO CountryInTheWorlds(Country,IsEnable) VALUES('Heard Island and McDonald Islands',1)
INSERT INTO CountryInTheWorlds(Country,IsEnable) VALUES('Honduras',1)
INSERT INTO CountryInTheWorlds(Country,IsEnable) VALUES('Hong Kong',1)
INSERT INTO CountryInTheWorlds(Country,IsEnable) VALUES('Hungary',1)
INSERT INTO CountryInTheWorlds(Country,IsEnable) VALUES('Iceland',1)
INSERT INTO CountryInTheWorlds(Country,IsEnable) VALUES('India',1)
INSERT INTO CountryInTheWorlds(Country,IsEnable) VALUES('Indonesia',1)
INSERT INTO CountryInTheWorlds(Country,IsEnable) VALUES('Iran',1)
INSERT INTO CountryInTheWorlds(Country,IsEnable) VALUES('Iraq',1)
INSERT INTO CountryInTheWorlds(Country,IsEnable) VALUES('Ireland',1)
INSERT INTO CountryInTheWorlds(Country,IsEnable) VALUES('Isle of Man',1)
INSERT INTO CountryInTheWorlds(Country,IsEnable) VALUES('Israel',1)
INSERT INTO CountryInTheWorlds(Country,IsEnable) VALUES('Italy',1)
INSERT INTO CountryInTheWorlds(Country,IsEnable) VALUES('Jamaica',1)
INSERT INTO CountryInTheWorlds(Country,IsEnable) VALUES('Japan',1)
INSERT INTO CountryInTheWorlds(Country,IsEnable) VALUES('Jersey',1)
INSERT INTO CountryInTheWorlds(Country,IsEnable) VALUES('Jordan',1)
INSERT INTO CountryInTheWorlds(Country,IsEnable) VALUES('Kazakhstan',1)
INSERT INTO CountryInTheWorlds(Country,IsEnable) VALUES('Kenya',1)
INSERT INTO CountryInTheWorlds(Country,IsEnable) VALUES('Kiribati',1)
INSERT INTO CountryInTheWorlds(Country,IsEnable) VALUES('Kosovo',1)
INSERT INTO CountryInTheWorlds(Country,IsEnable) VALUES('Kuwait',1)
INSERT INTO CountryInTheWorlds(Country,IsEnable) VALUES('Kyrgyzstan',1)
INSERT INTO CountryInTheWorlds(Country,IsEnable) VALUES('Laos',1)
INSERT INTO CountryInTheWorlds(Country,IsEnable) VALUES('Latvia',1)
INSERT INTO CountryInTheWorlds(Country,IsEnable) VALUES('Lebanon',1)
INSERT INTO CountryInTheWorlds(Country,IsEnable) VALUES('Lesotho',1)
INSERT INTO CountryInTheWorlds(Country,IsEnable) VALUES('Liberia',1)
INSERT INTO CountryInTheWorlds(Country,IsEnable) VALUES('Libya',1)
INSERT INTO CountryInTheWorlds(Country,IsEnable) VALUES('Liechtenstein',1)
INSERT INTO CountryInTheWorlds(Country,IsEnable) VALUES('Lithuania',1)
INSERT INTO CountryInTheWorlds(Country,IsEnable) VALUES('Luxembourg',1)
INSERT INTO CountryInTheWorlds(Country,IsEnable) VALUES('Macao',1)
INSERT INTO CountryInTheWorlds(Country,IsEnable) VALUES('Macedonia',1)
INSERT INTO CountryInTheWorlds(Country,IsEnable) VALUES('Madagascar',1)
INSERT INTO CountryInTheWorlds(Country,IsEnable) VALUES('Malawi',1)
INSERT INTO CountryInTheWorlds(Country,IsEnable) VALUES('Malaysia',1)
INSERT INTO CountryInTheWorlds(Country,IsEnable) VALUES('Maldives',1)
INSERT INTO CountryInTheWorlds(Country,IsEnable) VALUES('Mali',1)
INSERT INTO CountryInTheWorlds(Country,IsEnable) VALUES('Malta',1)
INSERT INTO CountryInTheWorlds(Country,IsEnable) VALUES('Marshall Islands',1)
INSERT INTO CountryInTheWorlds(Country,IsEnable) VALUES('Martinique',1)
INSERT INTO CountryInTheWorlds(Country,IsEnable) VALUES('Mauritania',1)
INSERT INTO CountryInTheWorlds(Country,IsEnable) VALUES('Mauritius',1)
INSERT INTO CountryInTheWorlds(Country,IsEnable) VALUES('Mayotte',1)
INSERT INTO CountryInTheWorlds(Country,IsEnable) VALUES('Mexico',1)
INSERT INTO CountryInTheWorlds(Country,IsEnable) VALUES('Micronesia',1)
INSERT INTO CountryInTheWorlds(Country,IsEnable) VALUES('Moldava',1)
INSERT INTO CountryInTheWorlds(Country,IsEnable) VALUES('Monaco',1)
INSERT INTO CountryInTheWorlds(Country,IsEnable) VALUES('Mongolia',1)
INSERT INTO CountryInTheWorlds(Country,IsEnable) VALUES('Montenegro',1)
INSERT INTO CountryInTheWorlds(Country,IsEnable) VALUES('Montserrat',1)
INSERT INTO CountryInTheWorlds(Country,IsEnable) VALUES('Morocco',1)
INSERT INTO CountryInTheWorlds(Country,IsEnable) VALUES('Mozambique',1)
INSERT INTO CountryInTheWorlds(Country,IsEnable) VALUES('Myanmar (Burma)',0)
INSERT INTO CountryInTheWorlds(Country,IsEnable) VALUES('Namibia',1)
INSERT INTO CountryInTheWorlds(Country,IsEnable) VALUES('Nauru',1)
INSERT INTO CountryInTheWorlds(Country,IsEnable) VALUES('Nepal',1)
INSERT INTO CountryInTheWorlds(Country,IsEnable) VALUES('Netherlands',1)
INSERT INTO CountryInTheWorlds(Country,IsEnable) VALUES('New Caledonia',1)
INSERT INTO CountryInTheWorlds(Country,IsEnable) VALUES('New Zealand',1)
INSERT INTO CountryInTheWorlds(Country,IsEnable) VALUES('Nicaragua',1)
INSERT INTO CountryInTheWorlds(Country,IsEnable) VALUES('Niger',1)
INSERT INTO CountryInTheWorlds(Country,IsEnable) VALUES('Nigeria',1)
INSERT INTO CountryInTheWorlds(Country,IsEnable) VALUES('Niue',1)
INSERT INTO CountryInTheWorlds(Country,IsEnable) VALUES('Norfolk Island',1)
INSERT INTO CountryInTheWorlds(Country,IsEnable) VALUES('North Korea',1)
INSERT INTO CountryInTheWorlds(Country,IsEnable) VALUES('Northern Mariana Islands',1)
INSERT INTO CountryInTheWorlds(Country,IsEnable) VALUES('Norway',1)
INSERT INTO CountryInTheWorlds(Country,IsEnable) VALUES('Oman',1)
INSERT INTO CountryInTheWorlds(Country,IsEnable) VALUES('Pakistan',0)
INSERT INTO CountryInTheWorlds(Country,IsEnable) VALUES('Palau',1)
INSERT INTO CountryInTheWorlds(Country,IsEnable) VALUES('Palestine',1)
INSERT INTO CountryInTheWorlds(Country,IsEnable) VALUES('Panama',1)
INSERT INTO CountryInTheWorlds(Country,IsEnable) VALUES('Papua New Guinea',1)
INSERT INTO CountryInTheWorlds(Country,IsEnable) VALUES('Paraguay',1)
INSERT INTO CountryInTheWorlds(Country,IsEnable) VALUES('Peru',1)
INSERT INTO CountryInTheWorlds(Country,IsEnable) VALUES('Phillipines',1)
INSERT INTO CountryInTheWorlds(Country,IsEnable) VALUES('Pitcairn',1)
INSERT INTO CountryInTheWorlds(Country,IsEnable) VALUES('Poland',1)
INSERT INTO CountryInTheWorlds(Country,IsEnable) VALUES('Portugal',1)
INSERT INTO CountryInTheWorlds(Country,IsEnable) VALUES('Puerto Rico',1)
INSERT INTO CountryInTheWorlds(Country,IsEnable) VALUES('Qatar',1)
INSERT INTO CountryInTheWorlds(Country,IsEnable) VALUES('Reunion',1)
INSERT INTO CountryInTheWorlds(Country,IsEnable) VALUES('Romania',1)
INSERT INTO CountryInTheWorlds(Country,IsEnable) VALUES('Russia',1)
INSERT INTO CountryInTheWorlds(Country,IsEnable) VALUES('Rwanda',1)
INSERT INTO CountryInTheWorlds(Country,IsEnable) VALUES('Saint Barthelemy',1)
INSERT INTO CountryInTheWorlds(Country,IsEnable) VALUES('Saint Helena',1)
INSERT INTO CountryInTheWorlds(Country,IsEnable) VALUES('Saint Kitts and Nevis',1)
INSERT INTO CountryInTheWorlds(Country,IsEnable) VALUES('Saint Lucia',1)
INSERT INTO CountryInTheWorlds(Country,IsEnable) VALUES('Saint Martin',1)
INSERT INTO CountryInTheWorlds(Country,IsEnable) VALUES('Saint Pierre and Miquelon',1)
INSERT INTO CountryInTheWorlds(Country,IsEnable) VALUES('Saint Vincent and the Grenadines',1)
INSERT INTO CountryInTheWorlds(Country,IsEnable) VALUES('Samoa',1)
INSERT INTO CountryInTheWorlds(Country,IsEnable) VALUES('San Marino',1)
INSERT INTO CountryInTheWorlds(Country,IsEnable) VALUES('Sao Tome and Principe',1)
INSERT INTO CountryInTheWorlds(Country,IsEnable) VALUES('Saudi Arabia',1)
INSERT INTO CountryInTheWorlds(Country,IsEnable) VALUES('Senegal',1)
INSERT INTO CountryInTheWorlds(Country,IsEnable) VALUES('Serbia',1)
INSERT INTO CountryInTheWorlds(Country,IsEnable) VALUES('Seychelles',1)
INSERT INTO CountryInTheWorlds(Country,IsEnable) VALUES('Sierra Leone',1)
INSERT INTO CountryInTheWorlds(Country,IsEnable) VALUES('Singapore',1)
INSERT INTO CountryInTheWorlds(Country,IsEnable) VALUES('Sint Maarten',1)
INSERT INTO CountryInTheWorlds(Country,IsEnable) VALUES('Slovakia',1)
INSERT INTO CountryInTheWorlds(Country,IsEnable) VALUES('Slovenia',1)
INSERT INTO CountryInTheWorlds(Country,IsEnable) VALUES('Solomon Islands',1)
INSERT INTO CountryInTheWorlds(Country,IsEnable) VALUES('Somalia',1)
INSERT INTO CountryInTheWorlds(Country,IsEnable) VALUES('South Africa',1)
INSERT INTO CountryInTheWorlds(Country,IsEnable) VALUES('South Georgia and the South Sandwich Islands',1)
INSERT INTO CountryInTheWorlds(Country,IsEnable) VALUES('South Korea',1)
INSERT INTO CountryInTheWorlds(Country,IsEnable) VALUES('South Sudan',1)
INSERT INTO CountryInTheWorlds(Country,IsEnable) VALUES('Spain',1)
INSERT INTO CountryInTheWorlds(Country,IsEnable) VALUES('Sri Lanka',1)
INSERT INTO CountryInTheWorlds(Country,IsEnable) VALUES('Sudan',1)
INSERT INTO CountryInTheWorlds(Country,IsEnable) VALUES('Suriname',1)
INSERT INTO CountryInTheWorlds(Country,IsEnable) VALUES('Svalbard and Jan Mayen',1)
INSERT INTO CountryInTheWorlds(Country,IsEnable) VALUES('Swaziland',1)
INSERT INTO CountryInTheWorlds(Country,IsEnable) VALUES('Sweden',1)
INSERT INTO CountryInTheWorlds(Country,IsEnable) VALUES('Switzerland',1)
INSERT INTO CountryInTheWorlds(Country,IsEnable) VALUES('Syria',1)
INSERT INTO CountryInTheWorlds(Country,IsEnable) VALUES('Taiwan',1)
INSERT INTO CountryInTheWorlds(Country,IsEnable) VALUES('Tajikistan',1)
INSERT INTO CountryInTheWorlds(Country,IsEnable) VALUES('Tanzania',1)
INSERT INTO CountryInTheWorlds(Country,IsEnable) VALUES('Thailand',1)
INSERT INTO CountryInTheWorlds(Country,IsEnable) VALUES('Timor-Leste (East Timor)',1)
INSERT INTO CountryInTheWorlds(Country,IsEnable) VALUES('Togo',1)
INSERT INTO CountryInTheWorlds(Country,IsEnable) VALUES('Tokelau',1)
INSERT INTO CountryInTheWorlds(Country,IsEnable) VALUES('Tonga',1)
INSERT INTO CountryInTheWorlds(Country,IsEnable) VALUES('Trinidad and Tobago',1)
INSERT INTO CountryInTheWorlds(Country,IsEnable) VALUES('Tunisia',1)
INSERT INTO CountryInTheWorlds(Country,IsEnable) VALUES('Turkey',1)
INSERT INTO CountryInTheWorlds(Country,IsEnable) VALUES('Turkmenistan',1)
INSERT INTO CountryInTheWorlds(Country,IsEnable) VALUES('Turks and Caicos Islands',1)
INSERT INTO CountryInTheWorlds(Country,IsEnable) VALUES('Tuvalu',1)
INSERT INTO CountryInTheWorlds(Country,IsEnable) VALUES('Uganda',1)
INSERT INTO CountryInTheWorlds(Country,IsEnable) VALUES('Ukraine',1)
INSERT INTO CountryInTheWorlds(Country,IsEnable) VALUES('United Arab Emirates',1)
INSERT INTO CountryInTheWorlds(Country,IsEnable) VALUES('United Kingdom',1)
INSERT INTO CountryInTheWorlds(Country,IsEnable) VALUES('United States',1)
INSERT INTO CountryInTheWorlds(Country,IsEnable) VALUES('United States Minor Outlying Islands',1)
INSERT INTO CountryInTheWorlds(Country,IsEnable) VALUES('Uruguay',1)
INSERT INTO CountryInTheWorlds(Country,IsEnable) VALUES('Uzbekistan',1)
INSERT INTO CountryInTheWorlds(Country,IsEnable) VALUES('Vanuatu',1)
INSERT INTO CountryInTheWorlds(Country,IsEnable) VALUES('Vatican City',1)
INSERT INTO CountryInTheWorlds(Country,IsEnable) VALUES('Venezuela',1)
INSERT INTO CountryInTheWorlds(Country,IsEnable) VALUES('Vietnam',1)
INSERT INTO CountryInTheWorlds(Country,IsEnable) VALUES('Virgin Islands, British',1)
INSERT INTO CountryInTheWorlds(Country,IsEnable) VALUES('Virgin Islands, US',1)
INSERT INTO CountryInTheWorlds(Country,IsEnable) VALUES('Wallis and Futuna',1)
INSERT INTO CountryInTheWorlds(Country,IsEnable) VALUES('Western Sahara',1)
INSERT INTO CountryInTheWorlds(Country,IsEnable) VALUES('Yemen',1)
INSERT INTO CountryInTheWorlds(Country,IsEnable) VALUES('Zambia',1)
INSERT INTO CountryInTheWorlds(Country,IsEnable) VALUES('Zimbabwe',1);